image: node:8.9.0

before_script:
  - npm install
  - npm run build
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/fsranking-front.git

deploy:
  only:
    - master
  stage: deploy
  script:
    - git push -f heroku master
